### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by rlowens** [dewgenenny/rtl_433_discoverandsubmit#1]
Trying to get this working. My rtl_433 doesn't sense my device so I'm trying to add it as a custom decode using
analyze_pulses true
then the recommended custom decoder
decoder n=oplinkremote,m=OOK_PWM,s=288,l=936,r=1040,g=0,t=259,y=0,bits=37

Trying to connect rtl_433_discoverandsubmit shows an empty screen:
![image](https://github.com/dewgenenny/rtl_433_discoverandsubmit/assets/35885181/dcf5c30d-12bd-4935-91b2-ae76df26eabc)

Then when I press q to quit I can see this output on the console:
---
PS C:\Users\rlowe> rtl_433_discoverandsubmit --mqtt_server homeassistant.local --mqtt_port 1883 --mqtt_username mqtt --mqtt_password REDACTED
Expecting pdcurses at: C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\unicurses/64 bit binaries/pdcdllu/pdcurses.dll
At start of load devices from file
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 1164, in _loop
    rc = self.loop_read()
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paho\mqtt\client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "C:\Users\rlowe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rtl_433_discoverandsubmit\modules\mqtt_client.py", line 32, in on_message
    device_id = f"{payload['model']}_{payload['id']}"
KeyError: 'id'
---

Using MQTT Explorer shows this for the device:
![image](https://github.com/dewgenenny/rtl_433_discoverandsubmit/assets/35885181/36b36cac-c725-403d-84f0-6a0c8a3f6b83)

So, my custom decoder doesn't provide an "id" (and I don't know how to set it up to provide one, or how to have it decode payloads to button names but I'm working on understanding rtl_433 still).

**Comment by dewgenenny** [comment]
Hey. I updated the mqtt_client.py to handle devices incoming without an ID. It now defaults to unknown. I'm hopeful this will fix your problem, however I'm not 100% as I haven't had time to recreate the error myself. 

Released as 0.1.6 - let me know if it fixes your issue

**Comment by rlowens** [comment]
Works! Thanks.
![image](https://github.com/dewgenenny/rtl_433_discoverandsubmit/assets/35885181/b5ec96a0-64e7-48b7-a4ff-a1ccf8de37fe)
